"""add_fk_c

Revision ID: 9b189f35287b
Revises: dbe253c4e6a8
Create Date: 2025-05-27 10:54:24.651997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b189f35287b'
down_revision: Union[str, None] = 'dbe253c4e6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('Categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'productos', 'categorias', ['Categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productos', type_='foreignkey')
    op.drop_column('productos', 'Categoria_id')
    # ### end Alembic commands ###
