"""add_productos_table

Revision ID: dbe253c4e6a8
Revises: bba08e884fd3
Create Date: 2025-05-27 10:39:57.344389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbe253c4e6a8'
down_revision: Union[str, None] = 'bba08e884fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('nombre', sa.String(length=40), nullable=True),
    sa.Column('modelo', sa.String(length=60), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productos')
    # ### end Alembic commands ###
